name: Test
on:
  push:
    branches: ['*']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_test

jobs:
  check_format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: node:18-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check prettier
        run: npx prettier --check .
  check_lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: node:18-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build test image
        uses: ./.github/templates/build
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: run test
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${IMAGE_NAME,,}:${{ github.ref_name }} 
          docker run --name app $IMAGE_NAME
          docker exec -i app npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: [test, check_format, check_lint]
    steps:
      - name: echo
        run: echo success
