name: Test
on:
  push:
    branches: ['*']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: test-actions
      - name: Build test image
        uses: ./.github/templates/build
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: set lower case owner name
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >>${GITHUB_ENV}
      - name: echo
        run: echo ${{ env.IMAGE_NAME }}
  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ github.IMAGE_NAME }}
      credentials:
        username: '${{ github.actor }}'
        password: '${{ secrets.github_token }}'
      ports:
        - 80
    steps:
      - name: ls
        run: ls
      - name: Check ESLint
        run: npm run lint
      - name: Check format
        run: npx prettier --check .
