name: Test

on:
  push:
    branches: ['*']

jobs:
  # check:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Check ESLint
  #       run: npm run lint

  #     - name: Check format
  #       run: npx prettier --check .

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: test-actions

      - name: ls
        run: ls ./.github/workflows/build/ -a

      - name: cat
        run: cat ./.github/workflows/build/action.yml

      - name: Build test image
        uses: ./.github/workflows/build
        with:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}_test
        env: ${{ secrets.YOUR_SECRET }}
