name: Test
on:
  push:
    branches: ['*']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_test
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: test-actions

      - name: Build test image
        uses: ./.github/templates/build
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    container:
      image: '${{ env.IMAGE_PATH }}'
      credentials:
        username: '${{ github.actor }}'
        password: '${{ secrets.github_token }}'
      env:
        NODE_ENV: development
        IMAGE_PATH: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      ports:
        - 80
    steps:
      - name: ls
        run: ls

      - name: Check ESLint
        run: npm run lint

      - name: Check format
        run: npx prettier --check .
