name: Test
on:
  push:
    branches: ['*']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build test image
        uses: ./.github/templates/build
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: echo
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${IMAGE_NAME,,}:${{ github.ref_name }} 
          echo "Starting container"
          docker run -d --name app $IMAGE_NAME
          echo "Test Prettier"
          docker exec -i app npx prettier --check .
          echo "Test ESLint"
          docker exec -i app npm run lint
          echo "Test App"
          docker exec -i app npm run test
