name: Test

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Build test image
        uses: ../workflow_templates/build.yml
        with:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}_test
